# Generated by Django 4.2.2 on 2023-07-05 01:12

import django.db.models.deletion

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    """Default migration"""

    dependencies = [
        ("companies", "0002_alter_company_description_alter_company_name"),
        ("departments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="company",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to="companies.company"
            ),
            preserve_default=False,
        ),
    ]
