---
version: '3.5'

services:
  nginx:
    build: ./nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_volume:./static
      - media_volume:./media
    depends_on:
      - django
  django:
    build: .
    volumes:
      - static_volume:./static
      - media_volume:./media
    env_file:
      - ./app/.env

volumes:
  static_volume:
  media_volume:
