# Generated by Django 4.2.2 on 2023-06-06 21:05

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    """Creates a migration"""

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(help_text="Company name", max_length=100)),
                (
                    "description",
                    models.CharField(
                        blank=True, help_text="Tiny company description", max_length=100
                    ),
                ),
            ],
        ),
    ]
