# Generated by Django 4.2.2 on 2023-06-28 22:21

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    """Companies migration"""

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="description",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
