# Generated by Django 4.2.2 on 2023-06-08 17:04

import django.db.models.deletion

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    """Migration"""

    dependencies = [
        ("employees", "0002_employee_company_employee_departments_employee_user"),
        ("overtime", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="overtimeregister",
            name="employee",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to="employees.employee"
            ),
            preserve_default=False,
        ),
    ]
