# Generated by Django 4.2.3 on 2023-07-13 22:52

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    """Add hours to overtime register model"""

    dependencies = [
        ("overtime", "0002_overtimeregister_employee"),
    ]

    operations = [
        migrations.AddField(
            model_name="overtimeregister",
            name="hours",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
