# Generated by Django 4.2.3 on 2023-08-08 20:30

import datetime

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    """Overtime creation date migration"""

    dependencies = [
        ("overtime", "0003_overtimeregister_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="overtimeregister",
            name="creation_date",
            field=models.DateField(default=datetime.date(2023, 8, 8)),
        ),
    ]
