# Generated by Django 4.2.3 on 2023-08-08 20:31

import datetime

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    """First type change"""

    dependencies = [
        ("overtime", "0004_overtimeregister_creation_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="overtimeregister",
            name="creation_date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 8, 8, 20, 31, 40, 651005, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
