# Generated by Django 4.2.3 on 2023-08-08 20:32

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    """Using django default kwargs"""

    dependencies = [
        ("overtime", "0005_alter_overtimeregister_creation_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="overtimeregister",
            name="creation_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
