# Generated by Django 4.2.2 on 2023-06-07 23:23

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    """Migration class"""

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("description", models.CharField(max_length=100)),
            ],
        ),
    ]
