# Generated by Django 4.2.3 on 2023-07-10 02:23

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    """Default file field added"""

    dependencies = [
        ("reports", "0003_alter_report_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="file",
            field=models.FileField(default=1, upload_to="reports"),
            preserve_default=False,
        ),
    ]
