# Generated by Django 4.2.2 on 2023-06-08 17:04

import django.db.models.deletion

from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    """Migration"""

    dependencies = [
        ("companies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("departments", "0001_initial"),
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="company",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to="companies.company"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="departments",
            field=models.ManyToManyField(to="departments.department"),
        ),
        migrations.AddField(
            model_name="employee",
            name="user",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
            preserve_default=False,
        ),
    ]
